# Generated by Django 3.0.6 on 2020-05-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yes_bouquets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
