# Generated by Django 3.0.6 on 2020-05-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yes_bouquets', '0002_auto_20200508_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
